# Generated by Django 4.0.4 on 2022-05-09 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0002_alter_guest_bought_alter_guest_deleted_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Guest',
            new_name='Guests',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
