# Generated by Django 4.0.4 on 2022-05-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0003_rename_guest_guests_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests',
            name='id',
        ),
        migrations.AlterField(
            model_name='guests',
            name='jmbag',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
