# Generated by Django 4.0.4 on 2022-05-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0005_alter_guests_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guests',
            name='jmbag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
