# Generated by Django 4.0.4 on 2022-05-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0006_guests_id_alter_guests_jmbag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
