# Generated by Django 4.0.4 on 2022-05-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0007_alter_guests_id_alter_users_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='privilage',
            new_name='privilege',
        ),
    ]
