# Generated by Django 4.0.4 on 2022-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0008_rename_privilage_users_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
