# Generated by Django 4.0.4 on 2022-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0010_alter_tags_name_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='bpught',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='tags',
            name='count',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='tags',
            name='entered',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
