# Generated by Django 4.0.4 on 2022-05-25 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0011_tags_bpught_tags_count_tags_entered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='bpught',
            new_name='bought',
        ),
    ]
