# Generated by Django 4.0.4 on 2022-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0012_rename_bpught_tags_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
