# Generated by Django 4.0.4 on 2022-06-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0013_alter_tags_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
