# Generated by Django 4.0.4 on 2022-06-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0014_remove_tags_id_remove_users_id_alter_tags_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
