# Generated by Django 4.0.4 on 2022-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0015_tags_id_users_id_alter_tags_name_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
