# Generated by Django 4.0.4 on 2022-06-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0016_alter_tags_id_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
