# Generated by Django 4.0.4 on 2022-06-21 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0021_lineup_sponsors_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lineup'),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/sponsors'),
        ),
    ]
