# Generated by Django 4.0.4 on 2022-06-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0022_alter_lineup_image_alter_sponsors_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='url',
            field=models.CharField(blank=True, default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='sponsors',
            name='url',
            field=models.CharField(blank=True, default='0', max_length=400),
        ),
    ]
