# Generated by Django 4.0.4 on 2022-07-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0023_alter_lineup_url_alter_sponsors_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='phone',
            new_name='email',
        ),
    ]
