# Generated by Django 4.0.4 on 2022-08-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0024_rename_phone_guests_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
