# Generated by Django 4.0.4 on 2022-09-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0025_lineup_slug_sponsors_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guests',
            old_name='deleted',
            new_name='confCode',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='url',
        ),
        migrations.AddField(
            model_name='sponsors',
            name='email',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='guestCap',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
    ]
