# Generated by Django 4.0.4 on 2022-09-13 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0026_rename_deleted_guests_confcode_remove_lineup_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='slug',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='sponsors',
            old_name='slug',
            new_name='order',
        ),
    ]
