# Generated by Django 4.0.4 on 2022-09-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0028_lineup_slug_tags_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
                ('bandName', models.CharField(blank=True, default='', max_length=49)),
                ('bookerName', models.CharField(blank=True, default='0', max_length=50)),
                ('bookerPhone', models.CharField(blank=True, default='0', max_length=50)),
            ],
        ),
    ]
