# Generated by Django 4.0.4 on 2022-09-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0030_sponsors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='visible',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
