# Generated by Django 4.0.4 on 2022-09-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0031_lineup_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailer',
            fields=[
                ('id', models.CharField(default=0, max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
