# Generated by Django 4.0.4 on 2022-09-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0033_mailer_mai_alter_mailer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailer',
            old_name='mai',
            new_name='message',
        ),
        migrations.AddField(
            model_name='mailer',
            name='subject',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='mailer',
            name='to_mail',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
