# Generated by Django 4.0.4 on 2022-09-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0034_rename_mai_mailer_message_mailer_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='id',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
    ]
