# Generated by Django 4.0.4 on 2022-10-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0037_sponsors_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='guests',
            field=models.CharField(blank=True, default='', max_length=49),
        ),
    ]
