# Generated by Django 4.0.4 on 2022-10-07 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0038_sponsors_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsors',
            name='guests',
        ),
    ]
