# Generated by Django 4.0.4 on 2022-10-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0039_remove_sponsors_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
