# Generated by Django 4.0.4 on 2022-10-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0040_alter_mailer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cjenik',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('tag', models.CharField(blank=True, default='0', max_length=50)),
                ('priceHR', models.CharField(blank=True, default='0', max_length=50)),
                ('priceEUR', models.CharField(blank=True, default='0', max_length=50)),
                ('amountL', models.CharField(blank=True, default='0', max_length=50)),
            ],
        ),
    ]
