# Generated by Django 4.0.4 on 2022-10-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0041_cjenik'),
    ]

    operations = [
        migrations.AddField(
            model_name='cjenik',
            name='order',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
