# Generated by Django 4.0.4 on 2022-10-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0044_rename_pricehr_cjenik_pricehrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='order',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
