# Generated by Django 4.0.4 on 2022-10-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0045_alter_sponsors_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cjenik',
            name='order',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='order',
            field=models.IntegerField(blank=True, default=''),
        ),
    ]
