# Generated by Django 4.0.4 on 2022-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0046_alter_cjenik_order_alter_lineup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='subject',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
