# Generated by Django 4.0.4 on 2022-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0048_alter_guests_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='guestsEnabled',
            field=models.CharField(blank=True, default='1', max_length=200),
        ),
    ]
