# Generated by Django 4.0.4 on 2023-06-13 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0049_sponsors_guestsenabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visibility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('visible', models.CharField(blank=True, default='0', max_length=50)),
            ],
        ),
    ]
