# Generated by Django 4.0.4 on 2023-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0050_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visibility',
            name='id',
        ),
        migrations.AlterField(
            model_name='visibility',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
