# Generated by Django 4.0.4 on 2023-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0051_remove_visibility_id_alter_visibility_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translations',
            fields=[
                ('key', models.CharField(default='', max_length=500, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, default='', max_length=5000)),
            ],
        ),
    ]
