# Generated by Django 4.0.4 on 2023-06-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0052_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='translations',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='translations',
            name='key',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
