# Generated by Django 4.0.4 on 2023-12-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0053_translations_id_alter_translations_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cjenik',
            name='priceHRK',
        ),
    ]
