# Generated by Django 4.0.4 on 2024-02-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0054_remove_cjenik_pricehrk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
