# Generated by Django 4.0.4 on 2024-02-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0059_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
