# Generated by Django 4.0.4 on 2024-02-07 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0061_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
