# Generated by Django 4.0.4 on 2024-02-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0062_alter_lineup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
