# Generated by Django 4.0.4 on 2024-02-08 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0063_alter_sponsors_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='email',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
