# Generated by Django 4.0.4 on 2024-02-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0064_alter_sponsors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailer',
            name='message',
            field=models.CharField(default=0, max_length=20000),
        ),
        migrations.AlterField(
            model_name='mailer',
            name='subject',
            field=models.CharField(default=0, max_length=20000),
        ),
        migrations.AlterField(
            model_name='mailer',
            name='to_mail',
            field=models.CharField(default=0, max_length=20000),
        ),
    ]
