# Generated by Django 4.0.4 on 2024-02-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0064_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
