# Generated by Django 4.0.4 on 2024-02-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0067_alter_guests_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='id',
            field=models.CharField(blank=True, default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
