# Generated by Django 4.0.4 on 2024-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0068_alter_guests_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
