# Generated by Django 4.0.4 on 2024-09-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0065_alter_mailer_message_alter_mailer_subject_and_more'),
        ('bruc', '0069_alter_guests_id'),
    ]

    operations = [
    ]
