# Generated by Django 4.2.16 on 2024-10-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0070_merge_20240903_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLeaderboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=50)),
                ('score', models.IntegerField(blank=True, default='')),
            ],
        ),
    ]
