# Generated by Django 4.2.16 on 2024-10-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0071_gameleaderboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='boughtTicketTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
