# Generated by Django 4.2.24 on 2025-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0073_alter_translations_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='biography',
            field=models.TextField(blank=True, default=''),
        ),
    ]
