# Generated by Django 4.2.24 on 2025-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0074_lineup_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
