# Generated by Django 4.2.24 on 2025-09-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0075_alter_lineup_order_alter_lineup_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrucosiFormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('jmbag', models.CharField(max_length=20)),
                ('gdpr_accepted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('redeemed', 'Redeemed')], default='invalid', max_length=10)),
            ],
        ),
    ]
