# Generated by Django 4.2.24 on 2025-10-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0076_brucosiformresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
