# Generated by Django 4.2.24 on 2025-11-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0077_alter_sponsors_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
