# Generated by Django 4.2.24 on 2026-03-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0078_alter_guests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
