# Generated by Django 4.2.24 on 2026-09-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0085_visibility_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brucosiformresponse',
            name='email',
        ),
    ]
