# Generated by Django 4.2.24 on 2026-09-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0087_convert_lineup_images_webp'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='mailError',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='guests',
            name='mailMessageId',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='guests',
            name='mailSentAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guests',
            name='mailStatus',
            field=models.CharField(choices=[('none', 'None'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='none', max_length=10),
        ),
    ]
