# Generated by Django 4.2.24 on 2026-09-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bruc', '0088_guests_mail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guests',
            name='mailStatus',
            field=models.CharField(choices=[('none', 'None'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='none', max_length=10),
        ),
    ]
