services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./media:/code/media

  vue:
    build:
      context: ./ui
      dockerfile: Dockerfile
    depends_on:
      - django
