name: Build and deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-frontend:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Add some env variables (REMOVE WHEN FIXED)
        run: |
          echo "VUE_APP_DJANGO_USER=comp" >> ./ui/.env
          echo "VUE_APP_DJANGO_PASS=Qf1EAPLhMv5c4CC8cbB0FUkB35rHSRcZ" >> ./ui/.env
          echo "VUE_APP_BASE_URL=/api" >> ./ui/.env
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./ui
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: |
            ksetcomp/brucifer-karte-2022-frontend:latest
            ksetcomp/brucifer-karte-2022-frontend:${{ github.sha }}

  build-backend:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          pull: true
          tags: |
            ksetcomp/brucifer-karte-2022-backend:latest
            ksetcomp/brucifer-karte-2022-backend:${{ github.sha }}

  notify-watchtower:
    runs-on: [self-hosted]
    needs: [build-frontend, build-backend]
    steps:
      - name: Notify Watchtower
        run: |
          curl -sL -v \
            --header 'Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}' \
            "${{ vars.WATCHTOWER_URL }}/v1/update"

